SELECT TOP (1000) [FirstName]
      ,[LastName]
      ,[Email]
      ,[ContactNumber]
      ,[LoyaltyMember]
      ,[City]
      ,[Province]
      ,[Store]
      ,[ProductName]
      ,[ProductID]
      ,[Category]
      ,[Supplier]
      ,[SaleID]
      ,[OrderDate]
      ,[CustomerID]
      ,[UnitPrice]
      ,[Quantity]
      ,[DiscountPercent]
      ,[TotalAmount]
      ,[PaymentMethod]
      ,[PaymentStatus]
      ,[SalesChannel]
      ,[SalesPerson]
      ,[StockLevel]
      ,[Promotion]
      ,[OrderStatus]
  FROM [urban_basket].[dbo].[urban_basket_sales_data]
